### ISSUE TITLE
Linux build broken

### ISSUE THREAD

**Issue by ranshe** [ARMmbed/mbed-cloud-client-example#7]
Following the instructions on https://cloud.mbed.com/docs/current/connecting/connecting.html, I get this error:

ubuntu@ip-172-31-25-20:~/mbed-cloud-client-example$ python pal-platform/pal-platform.py fullbuild --target x86_x64_NativeLinux_mbedtls --toolchain GCC --external ./../define.txt --name mbedCloudClientExample.elf
Traceback (most recent call last):
  File "pal-platform/pal-platform.py", line 29, in <module>
    import click
ImportError: No module named click

**Comment by teetak01** [comment]
Hi @ranshe did you install the development tools as suggested here: https://cloud.mbed.com/docs/current/cloud-requirements/tool-requirements.html

You are missing at least python `click`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2633

**Comment by ranshe** [comment]
@teetak01 - I did pip install mbed-cli as mention in https://github.com/ARMmbed/mbed-cli

**Comment by ranshe** [comment]
Did
pip install requests
pip install click
sudo apt-get install python-dev
export GCC_DIR=~/gcc-arm-none-eabi-7-2017-q4-major
export PATH=export PATH=~/gcc-arm-none-eabi-7-2017-q4-major/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin

Still get same error
 python pal-platform/pal-platform.py fullbuild --target x86_x64_NativeLinux_mbedtls --toolchain GCC --external ./../define.txt --name mbedCloudClientExample.elf
2018-04-25 18:05:19,316 - pal-platform - INFO - fullBuild running for target = x86_x64_NativeLinux_mbedtls with toolchain = GCC
2018-04-25 18:05:19,316 - pal-platform - INFO - Getting mbedtls from git
2018-04-25 18:05:19,317 - pal-platform - INFO - /home/ubuntu/mbed-cloud-client-example/pal-platform/Middleware/mbedtls/mbedtls already exists, updating from https://github.com/ARMmbed/mbedtls.git
2018-04-25 18:05:19,538 - pal-platform - INFO - Checking out from https://github.com/ARMmbed/mbedtls.git at mbedtls-2.4.2
Deployment for x86_x64_NativeLinux_mbedtls is successful.
Deployment instructions are in /home/ubuntu/mbed-cloud-client-example/pal-platform/x86_x64_NativeLinux_mbedtls.txt.
2018-04-25 18:05:19,547 - pal-platform - INFO - Generated /home/ubuntu/mbed-cloud-client-example/__x86_x64_NativeLinux_mbedtls/autogen.cmake
Generation for x86_x64_NativeLinux_mbedtls is successful, please run cmake & make from /home/ubuntu/mbed-cloud-client-example/__x86_x64_NativeLinux_mbedtls
2018-04-25 18:05:19,548 - pal-platform - INFO - Checking Environment for Toolchain - GCC
2018-04-25 18:05:19,548 - pal-platform - INFO - running cmake
2018-04-25 18:05:19,548 - pal-platform - INFO - setting environment: GCC_DIR = /home/ubuntu/gcc-arm-none-eabi-7-2017-q4-major
Traceback (most recent call last):
  File "pal-platform/pal-platform.py", line 1020, in <module>
    cli(sys.argv[1:])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "pal-platform/pal-platform.py", line 1007, in fullbuild
    runCmakeAndMake(out_dir, isDebug, toolchain, output, envPair, external, name, numOfBuildThreads)  # CMAKE + build debug version
  File "pal-platform/pal-platform.py", line 858, in runCmakeAndMake
    p = subprocess.Popen([command, argument1,argument2, argument3, argument4, argument5], cwd=folder)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ranshe** [comment]
ignore the strike through, I guess putting a string between ~ sign does that.
Testing: ~strike?~

**Comment by JaniSuonpera** [comment]
@ranshe This is x86 build for desktop Linux. You must Ubuntu native GCC version. I am using Ubuntu 16.05 LTS, installed gcc version is (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519.

**Comment by teetak01** [comment]
Could you undefine the GCC_ARM environmental flag? That is now incorrectly linking to ARM crosscompiler, when you actually need GCC linux compiler.

Also note that officially supported versions for both GCC and arm-none-eabi-gcc are the version 6 (you seem to have version 7).

**Comment by ranshe** [comment]
I'll try that when in front of PC.
I was trying to follow directions as given by arm, so can you please make the relevant changes to the docs?

**Comment by teetak01** [comment]
Sure, can you tell me where did you find the mention for GCC_ARM flag? I am unable to find it anywhere.

**Comment by ranshe** [comment]
I did not set this explicitly, must be part of the install scripts.
Unless you mean GCC_DIR flag, which I added since the build script sets it to /usr which I thought was wrong (and compilation failed)

**Comment by ranshe** [comment]
Regarding the GCC version - looking @ https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads, the download link points me to v7 - https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2?revision=375265d4-e9b5-41c8-bf23-56cbe927e156?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2017-q4-major

**Comment by ranshe** [comment]
@elm3 for visibility
Closing this since eventually I got it to work, however I still think that the docs (in the various places) needs to be consolidated and updated / have full details
